Button component
techshow-mu/techshow-website pull request #20
Opened 2021-03-25 07:37 UTC by Abdur-rahmaanJ

2021-03-25 07:41 UTC, Abdur-rahmaanJ commented
![button_component](https://user-images.githubusercontent.com/22630684/112436122-0a59d100-8d5f-11eb-8c54-0a6a0fe39877.png)

2021-03-25 08:01 UTC, Ludmilla13 submitted a review, later dismissed

2021-03-26 13:47 UTC, kherin requested changes

2021-03-26 13:47 UTC, kherin commented on src/app/button/button.component.ts
> +  constructor() {}
Could you add other `(input)`attributes to customize the styling of the button:
examples:
- elevation (drop-shadow)
- background-color
- text color
- border-radius
- disabled status
-

2021-03-28 17:29 UTC, Abdur-rahmaanJ commented
ok will work on it

2021-04-02 12:30 UTC, Abdur-rahmaanJ commented
![btn_component_v2](https://user-images.githubusercontent.com/22630684/113415649-b723f600-93d0-11eb-9099-5229d74a804d.png)

2021-04-02 14:51 UTC, kherin approved these changes
Looks Good 👍

2021-04-02 14:52 UTC, merged